spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3307/test
    username: root
    password: groot

mybatis:
  mapper-locations: classpath:mapper/*.xml
